<link href="jui/themes/default/style.css" rel="stylesheet" type="text/css" media="screen"/>
<link href="jui/themes/css/core.css?version=1.11" rel="stylesheet" type="text/css" media="screen"/>
<link href="resources/css/custom.css?version=1.20" rel="stylesheet" type="text/css" media="screen"/>
<link href="jui/themes/css/print.css" rel="stylesheet" type="text/css" media="print"/>
<link href="jui/uploadify/css/uploadify.css" rel="stylesheet" type="text/css" media="screen"/>
<!--
<link href="jui/treeTable/themes/default/treeTable.css" rel="stylesheet" type="text/css" />
-->
<link href="jui/keta/css/keta.css" rel="stylesheet" type="text/css" />
<link href="resources/css/dropdownlist.css?version=1.01" rel="stylesheet" type="text/css" />
<link rel="stylesheet" href="resources/poshtip/tip-yellow/tip-yellow.css" type="text/css" />
<link rel="stylesheet" href="resources/poshtip/tip-yellowsimple/tip-yellowsimple.css" type="text/css" />
<link rel="stylesheet" href="resources/mmGrid/css/mmGrid.css?version=1.03">
<link href="resources/treetable/css/jquery.treetable.css" rel="stylesheet" type="text/css" />
<link href="resources/treetable/css/jquery.treetable.theme.default.css?version=1.0" rel="stylesheet" type="text/css" />
<!--[if IE]>
<link href="jui/themes/css/ieHack.css" rel="stylesheet" type="text/css" media="screen"/>
<![endif]-->
<style type="text/css">
#header{height:38px}
#leftside, #container, #splitBar, #splitBarProxy{top:39px}
    
ul#nav_ul{list-style-type:none;width:100%;position:relative;height:27px;
font-family:"Trebuchet MS",Arial,sans-serif;font-size:13px;font-weight:bold;margin:0;padding:1px 0 0 0;}
ul#nav_ul li{display:block;float:left;margin:0 0 0 4px;height:27px;}
ul#nav_ul li.left{margin:0;}
ul#nav_ul li a{display:block;float:left;color:#fff;line-height:27px;text-decoration:none;padding:0 17px 0 18px;height:27px;}
ul#nav_ul li a.right{padding-right:19px;}
ul#nav_ul li a:hover{background:#2E4560;}
ul#nav_ul li a.current{color:#2E4560;background:#fff;}
ul#nav_ul li a.current:hover{color:#2E4560;background:#fff;}
#alarmTb td
{
    text-align: center;
    padding-bottom: 5px;
    padding-top: 5px
}
#alarmTb th
{
    text-align: center;
    padding-bottom: 5px;
    padding-top: 5px
}
</style>

<!--[if lte IE 9]>
<script src="js/speedup.js" type="text/javascript"></script>
<![endif]-->

<script src="jui/js/jquery-1.7.2.js" type="text/javascript"></script>
<script src="jui/js/jquery.cookie.js" type="text/javascript"></script>
<script src="jui/js/jquery.validate.js" type="text/javascript"></script>
<script src="jui/js/jquery.bgiframe.js" type="text/javascript"></script>
<script src="jui/js/jquery-form.js" type="text/javascript"></script>
<script src="jui/xheditor/xheditor-1.2.1.min.js" type="text/javascript"></script>
<script src="jui/xheditor/xheditor_lang/zh-cn.js" type="text/javascript"></script>
<script src="jui/uploadify/scripts/jquery.uploadify.js" type="text/javascript"></script>
<!-- <script src="resources/laydate/laydate.js?version=1.03" type="text/javascript"></script> -->
<script src="resources/laydate/laydate_1.js?version=1.03" type="text/javascript"></script>
<script src="resources/poshtip/jquery.poshytip.js" type="text/javascript" ></script>
<script src="jui/js/dwz.core.js" type="text/javascript"></script>
<script src="jui/js/dwz.util.date.js" type="text/javascript"></script>
<script src="jui/js/dwz.validate.method.js" type="text/javascript"></script>
<script src="jui/js/dwz.regional.zh.js" type="text/javascript"></script>
<script src="jui/js/dwz.barDrag.js" type="text/javascript"></script>
<script src="jui/js/dwz.drag.js" type="text/javascript"></script>
<script src="jui/js/dwz.tree.js" type="text/javascript"></script>
<script src="jui/js/dwz.accordion.js" type="text/javascript"></script>
<script src="jui/js/dwz.ui.js?version=1.0" type="text/javascript"></script>
<script src="jui/js/dwz.theme.js" type="text/javascript"></script>
<script src="jui/js/dwz.switchEnv.js" type="text/javascript"></script>
<script src="jui/js/dwz.alertMsg.js" type="text/javascript"></script>
<script src="jui/js/dwz.contextmenu.js" type="text/javascript"></script>
<script src="jui/js/dwz.navTab.js" type="text/javascript"></script>
<script src="jui/js/dwz.tab.js" type="text/javascript"></script>
<script src="jui/js/dwz.resize.js" type="text/javascript"></script>
<script src="jui/js/dwz.dialog.js" type="text/javascript"></script>
<script src="jui/js/dwz.dialogDrag.js" type="text/javascript"></script>
<script src="jui/js/dwz.sortDrag.js" type="text/javascript"></script>
<script src="jui/js/dwz.cssTable.js" type="text/javascript"></script>
<script src="jui/js/dwz.stable.js?version=1.01" type="text/javascript"></script>
<script src="jui/js/dwz.taskBar.js" type="text/javascript"></script>
<script src="jui/js/dwz.ajax.js" type="text/javascript"></script>
<script src="jui/js/dwz.pagination.js" type="text/javascript"></script>
<script src="jui/js/dwz.database.js?version=1.01" type="text/javascript"></script>
<script src="jui/js/dwz.datepicker.js" type="text/javascript"></script>
<script src="jui/js/dwz.effects.js" type="text/javascript"></script>
<script src="jui/js/dwz.panel.js" type="text/javascript"></script>
<script src="jui/js/dwz.checkbox.js" type="text/javascript"></script>
<script src="jui/js/dwz.history.js" type="text/javascript"></script>
<script src="jui/js/dwz.combox.js" type="text/javascript"></script>
<script src="jui/js/dwz.print.js" type="text/javascript"></script>
<!--
<script src="jui/treeTable/jquery.treeTable.min.js" type="text/javascript"></script>
-->
<script src="jui/keta/js/keta.js" type="text/javascript"></script>
<!--
<script src="bin/dwz.min.js" type="text/javascript"></script>
-->
<script src="jui/js/dwz.regional.zh.js" type="text/javascript"></script>
<script type="text/javascript" src="resources/highcharts_js/highcharts.js?version=1.01"></script>
<script type="text/javascript" src="resources/highcharts_js/exporting.js"></script>
<script type="text/javascript" src="resources/highcharts_js/charts.js?version=1.05"></script>
<script type="text/javascript" src="resources/highcharts_js/themes/grid.js"></script>
<%--
<script type="text/javascript" src="resources/highcharts_js/themes/sand-signika.js"></script>
 --%>
<script type="text/javascript" src="resources/js/dropdownlist.js?version=1.05" ></script>
<script type="text/javascript" src="resources/js/dropdownlist_1.js?version=1.02" ></script>
<script type="text/javascript" src="resources/mmGrid/js/mmGrid.js?version=1.0" ></script>
<script type="text/javascript" src="resources/fixTable/FixTable.js?version=1.04" ></script>
<script type="text/javascript" src="resources/treetable/js/jquery.treetable.js?version=1.0" ></script>

<script type="text/javascript" src="resources/echart/echarts.min.js" ></script>
<script type="text/javascript" src="resources/echart/echartsFunction.js" ></script>
<script type="text/javascript" src="resources/echart/data.js" ></script>
<script type="text/javascript" src="resources/echart/echartsChart.js?version=1.08" ></script>
<script type="text/javascript" src="resources/js/commonUtil.js?version=1.01" ></script>